{
  "hash": "2f1a2d10b06dfe0f3a24ed3fb1854177",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"3 Continuous-Time Linear State Spaces\"\njupyter: python3\nsuppress-bibliography: true\nlink-citations: false\n---\n\nThe state equation is local in time, but memory is not. The derivative only describes the next instant; the state at time $t$ contains the accumulated effect of all earlier inputs. Solving the differential equation turns the local update into an integral over the past, with the matrix exponential giving the weight assigned to each lag.[^continuous-systems-reference]\n\n## 3.1 Solving the differential equation {#sec-3-1}\n\nThe equation\n\n$$\nx'(t)=Ax(t)+Bu(t)\n$$\n\ndefines the model locally. It tells us how the state changes at an instant.\n\nMemory is a global question. An input value from an earlier time $s$ affects the state at a later time $t$ through the full solution of the differential equation.\n\nThe current state is a weighted accumulation of past inputs, and the matrix $A$ determines the weights.\n\nThe one-dimensional case removes matrix notation while keeping the basic mechanism.\n\nWhen $N=1$, the state space is $\\R$. The matrices $A$, $B$, and $C$ each have one entry. Write\n\n$$\nA=[a],\n\\qquad\nB=[b],\n\\qquad\nC=[c],\n$$\n\nwith $a,b,c\\in\\R$. Identifying each $1\\times 1$ matrix with its single entry, the state equation becomes\n\n$$\nx'(t)=ax(t)+bu(t).\n$$\n\nFirst ignore the input. If $u(t)=0$, then\n\n$$\nx'(t)=ax(t),\n$$\n\nwhose solution is\n\n$$\nx(t)=e^{at}x(0).\n$$\n\nThus $a$ controls the natural behaviour of the state. If $a<0$, the state decays. If $a>0$, the state grows. If $a=0$, the state remains constant when no input is present.\n\nInclude the input. Rewrite\n\n$$\nx'(t)-ax(t)=bu(t).\n$$\n\nMultiplying both sides by $e^{-at}$ gives\n\n$$\n\\frac{\\dd}{\\dd t}\\left(e^{-at}x(t)\\right)\n=\ne^{-at}bu(t).\n$$\n\nIntegrating from $0$ to $t$,\n\n$$\ne^{-at}x(t)-x(0)\n=\n\\int_0^t e^{-as}bu(s)\\dd s.\n$$\n\nMultiplying by $e^{at}$ gives\n\n$$\nx(t)\n=\ne^{at}x(0)\n+\n\\int_0^t e^{a(t-s)}bu(s)\\dd s.\n$$\n\nThe solution gives a precise picture of memory. The input value $u(s)$ contributes to $x(t)$ with weight\n\n$$\ne^{a(t-s)}b.\n$$\n\nThe quantity $t-s$ is the elapsed time between the input time $s$ and the present time $t$. If $a<0$, then inputs farther in the past receive smaller weight. The scalar state is therefore an exponentially weighted summary of the past input.\n\nFor higher-dimensional states, the same idea holds, but scalar exponentials are replaced by matrix exponentials.\n\nFor a square matrix $M$, the **matrix exponential** is defined by\n\n$$\ne^M\n=\n\\sum_{k=0}^{\\infty}\\frac{M^k}{k!}\n=\nI+M+\\frac{M^2}{2!}+\\frac{M^3}{3!}+\\cdots.\n$$\n\nThe reason this object appears is that it solves the matrix version of exponential growth and decay. The function $t\\mapsto e^{At}$ satisfies\n\n$$\n\\frac{\\dd}{\\dd t}e^{At}=Ae^{At},\n\\qquad\ne^{A\\cdot 0}=I.\n$$\n\nUsing the same integrating-factor argument as in the one-dimensional case, the solution of\n\n$$\nx'(t)=Ax(t)+Bu(t)\n$$\n\nis\n\n$$\n\\boxed{\nx(t)\n=\ne^{At}x(0)\n+\n\\int_0^t e^{A(t-s)}Bu(s)\\dd s.\n}\n$$\n\nWith the empty initial state $x(0)=0$,\n\n$$\nx(t)\n=\n\\int_0^t e^{A(t-s)}Bu(s)\\dd s.\n$$\n\nThis is the zero-state response, the part of the solution produced by the input alone.\n\nThe output is\n\n$$\ny(t)\n=\nCx(t)\n=\n\\int_0^t Ce^{A(t-s)}Bu(s)\\dd s.\n$$\n\nThe state equation and the convolution describe the same input-output map. The differential equation carries memory through $x(t)$; the integral removes the state and shows the weight assigned to every past time.\n\nThe convolution formula specifies how the past is compressed into the state and read out. The input at time $s$ first enters through $B$, then evolves for elapsed time $t-s$ through $e^{A(t-s)}$, and is finally read out through $C$.\n\nIn the MIMO case, the same expression holds with $u(s)\\in\\R^p$ and $y(t)\\in\\R^q$. The product\n\n$$\nCe^{A(t-s)}B\n$$\n\nis then a $q\\times p$ matrix. Its $(r,i)$ entry describes how the $i$th input coordinate affects the $r$th output coordinate after lag $t-s$.\n\n## 3.2 Lag and the impulse response {#sec-3-2}\n\nThe output formula is\n\n$$\ny(t)\n=\n\\int_0^t Ce^{A(t-s)}Bu(s)\\dd s.\n$$\n\nHere $s$ is the time at which an input value was received, and $t$ is the time at which the output is evaluated. Since $0\\le s\\le t$, the quantity\n\n$$\nt-s\n$$\n\nis the elapsed time between the input event and the output time. The elapsed time is called the lag. A recent input has small lag. A distant input has large lag.\n\nThe factor multiplying $u(s)$ is\n\n$$\nCe^{A(t-s)}B.\n$$\n\nIt depends on the input time $s$ only through the lag $t-s$. The system's response to a past input can therefore be described by a single function of the lag.\n\nDefine\n\n$$\nh(\\tau)=Ce^{A\\tau}B,\n\\qquad\n\\tau\\ge 0,\n$$\n\nand set\n\n$$\nh(\\tau)=0\n\\qquad\n\\text{for }\\tau<0.\n$$\n\nThen the output becomes\n\n$$\ny(t)\n=\n\\int_0^t h(t-s)u(s)\\dd s.\n$$\n\nThe output has convolution form:\n\n$$\ny=h*u.\n$$\n\nThe function $h$ is called the impulse response. It is the output pattern produced by an idealised unit input at one instant, and it gives the lag-dependent weight that connects each input value to later outputs.\n\nFor a MIMO system, $h(\\tau)$ is matrix-valued:\n\n$$\nh(\\tau)\\in\\R^{q\\times p}.\n$$\n\nEach lag has an input-output matrix rather than a single scalar weight.\n\nOn a grid of lags, $h(\\tau)=Ce^{A\\tau}B$ separates a scalar decay from a decayed rotation. The scalar system $A=[-1]$ gives a single exponential. The $2\\times2$ rotating system changes sign as it decays.\n\n::: {#e0cecfe8 .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nfrom ssm_book.numpy_ref.continuous import impulse_response\n\nts = np.array([0.0, 0.5, 1.0, 2.0, 4.0])\n\n# (i) scalar decay: A=[-1]\nh_decay = impulse_response([[-1.0]], [1.0], [1.0], ts).real.reshape(-1)\n\n# (ii) decayed rotation: eigenvalues -gamma +/- i*omega\ngamma, omega = 0.3, 2.0\nA = [[-gamma, omega], [-omega, -gamma]]\nh_rot = impulse_response(A, [1.0, 0.0], [1.0, 0.0], ts).real.reshape(-1)\n\nnp.round(np.stack([ts, h_decay, h_rot]), 4)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\narray([[ 0.    ,  0.5   ,  1.    ,  2.    ,  4.    ],\n       [ 1.    ,  0.6065,  0.3679,  0.1353,  0.0183],\n       [ 1.    ,  0.465 , -0.3083, -0.3587, -0.0438]])\n```\n:::\n:::\n\n\nAs the lag $\\tau$ increases, the scalar response decreases monotonically because a single negative eigenvalue gives a fading weight. The rotating response decays in magnitude but changes sign, reflecting the oscillation produced by the imaginary parts $\\pm\\omega$.\n\n![Figure 3.1. The impulse response $h(\\tau)=Ce^{A\\tau}B$ against the lag $\\tau$. The scalar system $A=[-1]$ gives a single fading exponential $e^{-\\tau}$ (blue). The decayed rotation, with eigenvalues $-0.3\\pm 2i$, gives $e^{-0.3\\tau}\\cos 2\\tau$ (orange), fading in magnitude but changing sign within the envelope $\\pm e^{-0.3\\tau}$ (dashed). The dots mark the lags $\\tau=0,0.5,1,2,4$. Both systems start at $h(0)=CB=1$.](../../figures/fig-3-1-lag.svg){fig-alt=\"Two impulse-response curves against lag tau: a blue monotone exponential, and an orange decaying oscillation bounded by a dashed envelope, with dots at tau = 0, 0.5, 1, 2, 4, and both curves starting at 1.\" fig-align=\"center\" width=\"75%\"}\n\nThe convolution also has a simple construction. Write $\\delta$ for the unit impulse, the idealised spike concentrated at time zero with $\\int \\delta(r-s)f(r)\\,\\dd r=f(s)$. Every input is itself a superposition of shifted impulses,\n\n$$\nu(r)=\\int_0^\\infty u(s)\\,\\delta(r-s)\\,\\dd s,\n$$\n\none spike at each instant $s$ weighted by $u(s)$. At output time $t$, causality restricts the contributing impulses to $0\\le s\\le t$. The system turns each shifted impulse $\\delta(\\cdot-s)$ into the shifted impulse response $h(t-s)$, and because the same matrices $A$, $B$, $C$ apply at every time, the response to the whole input is the matching superposition,\n\n$$\ny(t)=\\int_0^t h(t-s)\\,u(s)\\,\\dd s,\n$$\n\nthe same convolution as before. Each input impulse contributes one scaled, shifted copy of $h$, and the copies add up.\n\n![Figure 3.2. Convolution from shifted impulses. The input is a superposition of shifted impulses. The state space model sends an impulse at time $s$ to the shifted impulse response $h(t-s)$. By linearity the output is the matching superposition.](../../figures/fig-3-2-convolution.svg){fig-alt=\"Block diagram: input as an integral of shifted impulses, a linear time-invariant system box mapping delta to h, output as an integral of shifted impulse responses.\" fig-align=\"center\" width=\"92%\"}\n\n## 3.3 How the eigenvalues of $A$ shape memory {#sec-3-3}\n\nThe impulse response is\n\n$$\nh(\\tau)=Ce^{A\\tau}B.\n$$\n\nThus the behaviour of $h$ is controlled by $e^{A\\tau}$. The memory mechanisms are the functions that can appear inside this matrix exponential.\n\nThe clearest case is when $A$ can be diagonalised. Suppose $A$ has $N$ linearly independent eigenvectors\n\n$$\nv_1,\\dots,v_N\n$$\n\nwith corresponding eigenvalues\n\n$$\n\\lambda_1,\\dots,\\lambda_N.\n$$\n\nPlace the eigenvectors into the columns of a matrix\n\n$$\nV=\n\\begin{pmatrix}\n| & | & & |\\\\\nv_1 & v_2 & \\cdots & v_N\\\\\n| & | & & |\n\\end{pmatrix},\n$$\n\nand define\n\n$$\n\\Lambda=\\diag(\\lambda_1,\\dots,\\lambda_N).\n$$\n\nThen\n\n$$\nA=V\\Lambda V^{-1}.\n$$\n\nIn the eigenvector coordinate system, the action of $A$ separates into independent scalar modes. The matrix exponential becomes\n\n$$\ne^{A\\tau}\n=\nVe^{\\Lambda\\tau}V^{-1},\n$$\n\nwhere\n\n$$\ne^{\\Lambda\\tau}\n=\n\\diag\n\\left(\ne^{\\lambda_1\\tau},\n\\dots,\ne^{\\lambda_N\\tau}\n\\right).\n$$\n\nSo the impulse response is built from scalar exponential modes\n\n$$\ne^{\\lambda_i\\tau}.\n$$\n\nIf\n\n$$\n\\lambda_i=-\\alpha_i+i\\omega_i,\n$$\n\nthen\n\n$$\ne^{\\lambda_i\\tau}\n=\ne^{-\\alpha_i\\tau}\n\\left(\n\\cos(\\omega_i\\tau)\n+\ni\\sin(\\omega_i\\tau)\n\\right).\n$$\n\nThe decay rate $\\alpha_i$ controls growth or decay. The real part of the eigenvalue is $-\\alpha_i$, so a stable mode has $\\alpha_i>0$. The imaginary part $\\omega_i$ controls oscillation.\n\nThus:\n\n- eigenvalues with negative real part give decaying modes;\n- eigenvalues close to the imaginary axis decay slowly and can preserve information for longer;\n- eigenvalues with nonzero imaginary part give oscillatory modes;\n- eigenvalues with positive real part grow and are usually unstable.\n\nWhen $\\Real\\lambda_i<0$, a useful way to measure the timescale of the mode is its half-life. The **continuous half-life** is the lag $\\tau_{1/2}$ for which the magnitude has decayed by a factor of two:\n\n$$\ne^{(\\Real\\lambda_i)\\tau_{1/2}}=\\frac12.\n$$\n\nTherefore\n\n$$\n\\boxed{\n\\tau_{1/2}=\\frac{\\log 2}{-\\Real\\lambda_i}=\\frac{\\log 2}{\\alpha_i}.\n}\n$$\n\nThe half-life translates an eigenvalue into a memory length in continuous time.\n\nThe state matrix supplies the available memory modes through these eigenvalues.\n\nThe eigenvalues just used were complex, although the state matrix itself was real. Complex eigenvalues appear naturally when a real matrix contains rotations.\n\nIf $A$ is real and $\\lambda=-\\alpha+i\\omega$ is an eigenvalue, then its complex conjugate $\\bar\\lambda=-\\alpha-i\\omega$ is also an eigenvalue. The corresponding complex modes combine to produce real sine and cosine terms. Thus complex eigenvalues do not force the state or output to become complex. They are often a compact way of describing a real two-dimensional rotation.\n\nThe simplest real rotation already appears in two dimensions. The matrix\n\n$$\n\\begin{pmatrix}\n0 & \\omega\\\\\n-\\omega & 0\n\\end{pmatrix}\n$$\n\nhas eigenvalues $\\pm i\\omega$, but its action on $\\R^2$ is planar rotation. Adding a negative multiple of the identity makes that rotation decay.\n\nThe diagonalisable case explains the main intuition, but not every matrix has a full set of eigenvectors. The same memory picture still holds, with one additional feature.\n\nA Jordan block with eigenvalue $\\lambda$ has the form\n\n$$\nJ=\\lambda I+R,\n$$\n\nwhere $R$ is nilpotent, meaning that some power of $R$ is zero. Since $\\lambda I$ and $R$ commute,\n\n$$\ne^{J\\tau}=e^{\\lambda\\tau}e^{R\\tau}.\n$$\n\nIf the block has size $r$, then $R^r=0$, so\n\n$$\ne^{R\\tau}\n=\nI+\\tau R+\\frac{\\tau^2}{2!}R^2+\\cdots+\\frac{\\tau^{r-1}}{(r-1)!}R^{r-1}.\n$$\n\nThus a non-diagonalisable block contributes exponential terms multiplied by polynomials in the lag:\n\n$$\n\\tau^m e^{\\lambda\\tau}.\n$$\n\nThe real part of $\\lambda$ still controls exponential growth or decay. The Jordan structure adds polynomial factors on top of that exponential behaviour. For $\\Real\\lambda=-\\alpha<0$ the weight $\\tau^m e^{-\\alpha\\tau}$ first grows like $\\tau^m$ and only then decays, peaking near $\\tau=m/\\alpha$, so a non-diagonalisable mode weights inputs at an intermediate lag most heavily rather than the most recent ones.\n\n![Figure 3.3. The real part of an eigenvalue is a memory length. Each curve is $e^{-\\alpha\\tau}$ for a decay rate $\\alpha>0$. The half-life $\\tau_{1/2}=\\log 2/\\alpha$ is marked on one.](../../figures/fig-3-3-decay.svg){fig-alt=\"Several exponential decay curves with a half-life construction on one.\" fig-align=\"center\" width=\"80%\"}\n\n![Figure 3.4. An eigenvalue $\\lambda=-\\alpha+i\\omega$ of $A$ in the complex plane, with decay rate $\\alpha>0$ so that $\\Real\\lambda=-\\alpha$ lies in the shaded stable region $\\Real\\lambda<0$. The decay rate $\\alpha$ sets the fading and the imaginary part $\\omega$ the oscillation frequency. The distance from the origin $|\\lambda|$ measures the mode's overall rate, and the angle $\\theta$ from the negative real axis its balance of decay to oscillation. For a real matrix the eigenvalues occur in conjugate pairs $\\lambda,\\bar\\lambda$, mirrored across the real axis.](../../figures/fig-3-4-eigenvalues.svg){fig-alt=\"Complex plane with the stable left half-plane shaded, a conjugate pair on a circle of radius the eigenvalue magnitude, and the angle from the negative real axis.\" fig-align=\"center\" width=\"70%\"}\n\n## 3.4 Fading memory and oscillatory memory {#sec-3-4}\n\nThe memory of the model is built from modes of $A$. The two simplest mechanisms are **fading memory** and **oscillatory memory**.\n\nA real negative eigenvalue gives a decaying exponential, which behaves like a fading average of the past. A complex conjugate pair gives rotation, which can represent oscillatory or phase-like information.\n\nTwo examples isolate these mechanisms.\n\n### A fading one-dimensional memory {#sec-3-4-1}\n\nTake $N=1$ and write\n\n$$\nA=[a],\n\\qquad\nB=[b],\n\\qquad\nC=[c],\n$$\n\nwith\n\n$$\na<0.\n$$\n\nThe impulse response is\n\n$$\nh(\\tau)=ce^{a\\tau}b,\n\\qquad\n\\tau\\ge 0.\n$$\n\nThe output is\n\n$$\ny(t)\n=\ncb\\int_0^t e^{a(t-s)}u(s)\\dd s.\n$$\n\nThe output is an exponentially weighted running total of the past input. The rate $-a$ determines how quickly older information is discounted. The half-life from @sec-3-3 turns this rate into a number. For $a=-1$ the half-life is $\\log 2\\approx 0.69$, so a lag of $0.69$ halves the weight, and at lag $2$ the weight is $e^{-2}\\approx 0.135$, the value the dots in Figure 3.1 mark on the blue curve.\n\nThis is the continuous-time exponential moving average, with $-a$ playing the part of the forgetting rate. A small $-a$ keeps a long memory and a large $-a$ forgets almost at once.\n\nFor example, if\n\n$$\nu(s)=1\n$$\n\nfor all $s$, then\n\n$$\nx(t)\n=\nb\\int_0^t e^{a(t-s)}\\dd s\n=\n\\frac{b}{a}\\left(e^{at}-1\\right).\n$$\n\nSince $a<0$,\n\n$$\nx(t)\\to -\\frac{b}{a}\n\\qquad\n\\text{as }t\\to\\infty.\n$$\n\nThe state approaches a finite value because old input is continuously discounted. The limit has a direct reading. Writing $-b/a=b\\int_0^\\infty e^{a\\tau}\\dd\\tau$ shows it as $b$ times the total weight the system ever assigns to the past, so $-b/a$ is the gain the model applies to a constant input.\n\n### A rotating two-dimensional memory {#sec-3-4-2}\n\nA one-dimensional state can only move along a line. It can grow, decay, or stay fixed, but it cannot rotate. To get rotation, the state must have at least two dimensions.\n\nRotation matters because not all memory is well described as a fading average. Some signals contain periodic or phase-like structure. A rotating state can represent this kind of information.\n\nConsider\n\n$$\nA=\n\\begin{pmatrix}\n-\\gamma & \\omega\\\\\n-\\omega & -\\gamma\n\\end{pmatrix},\n\\qquad\n\\gamma\\ge 0,\n\\quad\n\\omega>0.\n$$\n\nThe parameter $\\gamma$ controls decay, while $\\omega$ controls angular speed. Write\n\n$$\nA=-\\gamma I+\\omega J,\n\\qquad\nJ=\n\\begin{pmatrix}\n0 & 1\\\\\n-1 & 0\n\\end{pmatrix}.\n$$\n\nThe matrix $J$ is the basic generator of planar rotation. It satisfies\n\n$$\nJ^2=-I.\n$$\n\nThe identity gives the same sine-cosine pattern as the scalar exponential of an imaginary number. Since $-\\gamma I$ commutes with $\\omega J$, the exponential factors as $e^{A\\tau}=e^{-\\gamma\\tau}e^{\\omega J\\tau}$. Splitting the series for $e^{\\omega J\\tau}$ into even and odd powers and using $J^2=-I$ collects the even terms into $\\cos(\\omega\\tau)I$ and the odd terms into $\\sin(\\omega\\tau)J$, exactly as for $e^{i\\theta}$. Therefore\n\n$$\ne^{A\\tau}\n=\ne^{-\\gamma\\tau}\n\\left(\n\\cos(\\omega\\tau)I+\n\\sin(\\omega\\tau)J\n\\right),\n$$\n\nor explicitly,\n\n$$\ne^{A\\tau}\n=\ne^{-\\gamma\\tau}\n\\begin{pmatrix}\n\\cos(\\omega\\tau) & \\sin(\\omega\\tau)\\\\\n-\\sin(\\omega\\tau) & \\cos(\\omega\\tau)\n\\end{pmatrix}.\n$$\n\nThe state rotates at angular frequency $\\omega$, while its magnitude decays at rate $\\gamma$.\n\nThe eigenvalues are\n\n$$\n-\\gamma\\pm i\\omega.\n$$\n\nThe eigenvalues match the general interpretation. The real part $-\\gamma$ gives decay, and the imaginary parts $\\pm\\omega$ give oscillation.\n\nA state space model can represent more than a fading average. By combining decaying and oscillating modes, a finite-dimensional state can encode both slowly varying and phase-like summaries of the input history.\n\nThe modes describe what the state can remember. They do not by themselves give a fixed convolution kernel. A fixed kernel appears only when the input-output map is both linear and time-invariant.\n\n## 3.5 Linearity and time-invariance {#sec-3-5}\n\nThe model is **linear** because $x$ and $u$ enter both equations only through matrix products:\n\n$$\nx'(t)=Ax(t)+Bu(t),\n\\qquad\ny(t)=Cx(t).\n$$\n\nFor zero initial state, the input-output map $T:u\\mapsto y$ therefore satisfies\n\n$$\nT(\\alpha u_1+\\beta u_2)\n=\n\\alpha T(u_1)+\\beta T(u_2)\n$$\n\nfor scalars $\\alpha,\\beta$.\n\nBy the convolution formula\n\n$$\ny(t)=\\int_0^t h(t-s)u(s)\\dd s.\n$$\n\nThe input $u$ appears only linearly inside the integral.\n\nLinearity is restrictive. The model cannot multiply state coordinates by the input, cannot square the input, and cannot apply different dynamics depending on the content of the input. Nonlinear components can be placed around a state space model, but the state space model defined here is linear.\n\nThe same matrices control a second property. The model is **time-invariant** because the same matrices\n\n$$\nA,\n\\qquad\nB,\n\\qquad\nC\n$$\n\nare used at every time. The rule does not change as $t$ changes.\n\nA delayed input pattern produces the same output pattern delayed by the same amount. The model does not change its rule merely because the same event happens later.\n\nThe impulse response, the kernel of this convolution, expresses time-invariance directly. The contribution of $u(s)$ to $y(t)$ depends on the lag\n\n$$\nt-s,\n$$\n\nnot on the absolute values of $s$ and $t$ separately. A single function $h$ therefore applies at every time:\n\n$$\ny(t)=\\int_0^t h(t-s)u(s)\\dd s.\n$$\n\nLinearity and time-invariance together are abbreviated LTI. Their main consequence is the existence of a fixed convolution kernel.\n\nIf the matrices were allowed to vary with time, the weight from $u(s)$ to $y(t)$ would depend on the matrices used throughout the interval from $s$ to $t$. The map could still be linear if those matrices were fixed in advance, but it would no longer be time-invariant, and the weight from $u(s)$ to $y(t)$ would depend on $s$ and $t$ separately rather than only on the lag $t-s$.\n\nIf the matrices were allowed to depend on the input being processed, the situation would change further. Then the input would not merely pass through a fixed linear map. It would also help determine the map. The resulting input-output transformation would generally not be linear.\n\n## 3.6 From a scalar input to model dimension $\\dmodel$ {#sec-3-6}\n\nA scalar input gives one stream. Neural sequence models usually store a vector at each position. If the model dimension is $\\dmodel$, then the input at time $t$ has the form\n\n$$\nu(t)\\in\\R^{\\dmodel}.\n$$\n\nWrite its coordinates as\n\n$$\nu(t)=\n\\begin{pmatrix}\nu_1(t)\\\\\nu_2(t)\\\\\n\\vdots\\\\\nu_{\\dmodel}(t)\n\\end{pmatrix}.\n$$\n\nA coordinate-wise state space layer applies one SISO state space model to each coordinate:\n\n$$\nx_d'(t)=A_d x_d(t)+B_d u_d(t),\n\\qquad\ny_d(t)=C_d x_d(t),\n\\qquad\nd=1,\\dots,\\dmodel.\n$$\n\nThere is no mixing between coordinates inside these SISO state space models. The alternative would be one MIMO system with $p=q=\\dmodel$, which has a $\\dmodel\\times\\dmodel$ matrix-valued impulse response at every lag and couples all coordinates through one shared state. The coordinate-wise layer instead gives $\\dmodel$ scalar kernels, each with its own state of dimension $N$, for $O(\\dmodel N)$ total state against the coupled alternative. The independent layout is cheaper and keeps each coordinate readable on its own.\n\nAny mixing across the model dimension is therefore performed outside this coordinate-wise state space operation, usually by position-wise linear maps surrounding the state space model.\n\nThe word \"channel\" is sometimes used in the literature for one coordinate of the model dimension. The term **coordinate** is used here unless quoting that terminology from a specific source.\n\nEach coordinate requires its own scalar kernel $Ce^{A\\tau}B$. After discretisation, these kernels must be generated at a cost compatible with long sequences.\n\n## 3.7 Notation {#sec-3-7}\n\n| Symbol | Meaning | Type |\n|---|---|---|\n| $h(\\tau)$ | impulse response $Ce^{A\\tau}B$ | scalar or $q\\times p$ matrix |\n| $\\lambda_i$ | eigenvalues of $A$ | $\\C$ |\n| $\\tau_{1/2}$ | continuous half-life of a decaying mode | $\\R_{>0}$ |\n\n[^continuous-systems-reference]: The continuous-time linear state space model, its solution by the matrix exponential, and the impulse response are standard in linear systems theory. The integrating-factor solution $x(t)=e^{At}x(0)+\\int_0^t e^{A(t-s)}Bu(s)\\dd s$, the eigenvalue decomposition of $e^{A\\tau}$, and the Jordan-form correction are treated in standard accounts of linear systems [@kailath1980].\n\n## Summary {.unnumbered}\n\nSolving the continuous-time state equation turns a local differential equation into a memory formula. With zero initial state,\n\n$$\nx(t)=\\int_0^t e^{A(t-s)}Bu(s)\\,\\dd s.\n$$\n\nThe lag $\\tau=t-s$ enters through $e^{A\\tau}$. Stable eigenvalues make old inputs fade; complex eigenvalues add oscillation as well as decay.\n\nReading the state with $C$ gives the impulse response\n\n$$\nh(\\tau)=Ce^{A\\tau}B.\n$$\n\nThe same model can therefore be viewed as a recurrence in continuous time or as a convolution over the past. The initial condition adds a homogeneous term $Ce^{At}x(0)$; the input-driven memory is the integral term.\n\n## Exercises {.unnumbered}\n\n1. Take the state equation $x'(t)=Ax(t)+Bu(t)$ with $u(t)=0$ for all $t$. Show that $x(t)=e^{At}x(0)$ by differentiating $e^{At}x(0)$ and using $\\frac{\\dd}{\\dd t}e^{At}=Ae^{At}$, and confirm that it has the correct value at $t=0$.\n\n   ::: {.callout-tip collapse=\"true\"}\n   ## Solution\n\n   With $u\\equiv 0$ the equation is $x'(t)=Ax(t)$. Differentiate the candidate $x(t)=e^{At}x(0)$, treating $x(0)$ as a constant vector:\n\n   $$\n   \\frac{\\dd}{\\dd t}\\bigl(e^{At}x(0)\\bigr)\n   =\\Bigl(\\tfrac{\\dd}{\\dd t}e^{At}\\Bigr)x(0)\n   =Ae^{At}x(0)\n   =Ax(t).\n   $$\n\n   So the candidate satisfies $x'(t)=Ax(t)$. At $t=0$, $e^{A\\cdot 0}=I$, hence $x(0)=Ix(0)=x(0)$, the prescribed initial value. The candidate solves the equation and matches the initial condition, and the linear initial-value problem has a unique solution, so $x(t)=e^{At}x(0)$.\n   :::\n\n2. Starting from $\\frac{\\dd}{\\dd t}\\!\\left(e^{-At}x(t)\\right)=e^{-At}Bu(t)$, integrate from $0$ to $t$ and recover the zero-state response $x(t)=\\int_0^t e^{A(t-s)}Bu(s)\\dd s$ when $x(0)=0$. State where the assumption $x(0)=0$ is used.\n\n   ::: {.callout-tip collapse=\"true\"}\n   ## Solution\n\n   Integrate the given identity from $0$ to $t$, using $s$ as the variable of integration:\n\n   $$\n   e^{-At}x(t)-e^{-A\\cdot 0}x(0)\n   =\\int_0^t e^{-As}Bu(s)\\dd s.\n   $$\n\n   Since $e^{-A\\cdot 0}=I$, the left side is $e^{-At}x(t)-x(0)$. Multiply through by $e^{At}$:\n\n   $$\n   x(t)\n   =e^{At}x(0)\n   +\\int_0^t e^{A(t-s)}Bu(s)\\dd s,\n   $$\n\n   where $e^{At}e^{-As}=e^{A(t-s)}$ because $At$ and $-As$ commute. The assumption $x(0)=0$ is used only to drop the term $e^{At}x(0)$, leaving the zero-state response $x(t)=\\int_0^t e^{A(t-s)}Bu(s)\\dd s$. The convolution part is present regardless of the initial state; $x(0)=0$ removes the free decay of the initial condition.\n   :::\n\n3. Write a function that evaluates the impulse response $h(\\tau)=Ce^{A\\tau}B$ on a grid of lags, using a matrix exponential routine. For the scalar decay $A=[-1]$, $B=[1]$, $C=[1]$, check that your values match $e^{-\\tau}$ to within floating-point error, and report the largest absolute difference over the grid.\n\n   ::: {.callout-tip collapse=\"true\"}\n   ## Solution\n\n   `impulse_response` forms $Ce^{A\\tau}B$ at each lag with `scipy.linalg.expm`. For the scalar system the matrix exponential reduces to $e^{-\\tau}$, so the computed values should reproduce $e^{-\\tau}$.\n\n   ```python\n   import numpy as np\n   from ssm_book.numpy_ref.continuous import impulse_response\n\n   ts = np.linspace(0.0, 5.0, 51)\n   h = impulse_response([[-1.0]], [1.0], [1.0], ts).real.reshape(-1)\n   print(np.max(np.abs(h - np.exp(-ts))))\n   ```\n\n   The largest absolute difference over the grid is at the floating-point level and prints as $0.0$ in this run; the intended check is agreement within a small tolerance, not bit-for-bit equality, because a matrix-exponential routine is a numerical algorithm rather than a symbolic simplifier. A negative real eigenvalue gives a single fading exponential, the simplest form of memory.\n   :::\n\n4. For the decayed rotation $A=\\begin{pmatrix}-\\gamma & \\omega\\\\ -\\omega & -\\gamma\\end{pmatrix}$, the eigenvalues are $-\\gamma\\pm i\\omega$. Compute the impulse response with $B=(1,0)^\\top$ and $C=(1,0)$ for three settings: $(\\gamma,\\omega)=(1,0)$, $(0.1,0)$, and $(0.3,2)$. Describe how the decay rate and the presence of oscillation change across the three, and relate each to the eigenvalues.\n\n   ::: {.callout-tip collapse=\"true\"}\n   ## Solution\n\n   With $B=(1,0)^\\top$ and $C=(1,0)$ the impulse response reads off the top-left entry of $e^{A\\tau}$, which is $e^{-\\gamma\\tau}\\cos(\\omega\\tau)$.\n\n   ```python\n   import numpy as np\n   from ssm_book.numpy_ref.continuous import impulse_response\n\n   ts = np.array([0.0, 0.5, 1.0, 2.0, 4.0])\n   for gamma, omega in [(1.0, 0.0), (0.1, 0.0), (0.3, 2.0)]:\n       A = [[-gamma, omega], [-omega, -gamma]]\n       h = impulse_response(A, [1.0, 0.0], [1.0, 0.0], ts).real.reshape(-1)\n       print((gamma, omega), np.round(h, 4))\n   ```\n\n   On the lags $\\tau=0,0.5,1,2,4$ this gives\n\n   $$\n   \\begin{aligned}\n   (\\gamma,\\omega)&=(1,0): && 1,\\ 0.6065,\\ 0.3679,\\ 0.1353,\\ 0.0183,\\\\\n   (\\gamma,\\omega)&=(0.1,0): && 1,\\ 0.9512,\\ 0.9048,\\ 0.8187,\\ 0.6703,\\\\\n   (\\gamma,\\omega)&=(0.3,2): && 1,\\ 0.4650,\\ -0.3083,\\ -0.3587,\\ -0.0438.\n   \\end{aligned}\n   $$\n\n   With $\\omega=0$ the eigenvalues are the real pair $-\\gamma,-\\gamma$ and the response is a pure decay $e^{-\\gamma\\tau}$, with no sign change. Comparing the first two rows, $\\gamma=1$ forgets quickly while $\\gamma=0.1$ decays ten times more slowly and still retains most of its weight at $\\tau=4$. The third row has eigenvalues $-0.3\\pm 2i$: the magnitude decays at rate $\\gamma=0.3$, but the imaginary part $\\omega=2$ rotates the state, so the response changes sign and is no longer monotone. The real part of the eigenvalue sets the decay rate; the imaginary part sets the oscillation.\n   :::\n\n5. Suppose $A$ has an eigenvalue $\\lambda$ with $\\Real\\lambda>0$. Explain why the corresponding mode of $e^{A\\tau}$ grows without bound as $\\tau$ increases. If that mode is both excited by $B$ and read by $C$, explain why the impulse response $h(\\tau)=Ce^{A\\tau}B$ does not define a fading memory. Contrast this with $\\Real\\lambda<0$ and with $\\Real\\lambda=0$.\n\n   ::: {.callout-tip collapse=\"true\"}\n   ## Solution\n\n   In the eigenbasis a mode for the eigenvalue $\\lambda$ evolves as $e^{\\lambda\\tau}$, with magnitude $|e^{\\lambda\\tau}|=e^{(\\Real\\lambda)\\tau}$. With $\\Real\\lambda>0$ this magnitude grows without bound as $\\tau\\to\\infty$. Whenever $B$ excites this mode and $C$ reads it, the impulse response $h(\\tau)=Ce^{A\\tau}B$ inherits a term proportional to $e^{(\\Real\\lambda)\\tau}$ and therefore grows rather than fades. A fading memory requires distant inputs to receive smaller weight, that is $h(\\tau)\\to 0$; a growing mode gives the opposite, with the oldest inputs weighted most heavily, and the convolution $\\int_0^t h(t-s)u(s)\\dd s$ need not even converge as $t\\to\\infty$.\n\n   When $\\Real\\lambda<0$ the magnitude is $e^{-\\alpha\\tau}\\to 0$ (decay rate $\\alpha>0$), so the mode fades and contributes a decaying weight, the fading-memory regime. When $\\Real\\lambda=0$ the magnitude is $e^{0}=1$ for all $\\tau$: the mode neither grows nor decays. The input is then remembered with undiminished weight (a constant, if $\\omega=0$, or an undamped oscillation $\\cos\\omega\\tau$ otherwise), so the memory persists rather than fades and sits on the boundary between the two regimes.\n   :::\n\n",
    "supporting": [
      "02-continuous-time_files"
    ],
    "filters": [],
    "includes": {}
  }
}