<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3 Continuous-Time Linear State Spaces – State Space Models</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<link href="../../chapters/02-foundations/02-continuous-time.qmd#sec-3-1" rel="next">
<link href="../../chapters/02-foundations/01-state-as-memory.qmd#footnotes" rel="prev">
<link href="../../misc/icon-blue.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-0fee082c8b819d3f39cef6e571aa4bc4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-c27bd8c5a8766f1874de3d4a50411227.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-0fee082c8b819d3f39cef6e571aa4bc4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!--
  Shared math macros for the HTML build; injected into every page's <head> via
  `include-in-header` in _quarto.yml. Keep in sync with _macros.tex.
  Backslashes are doubled for the JS string; multi-argument macros use the
  ["{body}", argcount] form (see `inner`).
-->
<script>
window.MathJax = {
  tex: {
    macros: {
      R: "{\\mathbb{R}}",
      C: "{\\mathbb{C}}",
      N: "{\\mathbb{N}}",
      dd: "{\\,\\mathrm{d}}",
      dmodel: "{d_{\\mathrm{model}}}",
      Bbatch: "{\\mathsf{B}}",
      feed: "{D_{\\mathrm{feed}}}",
      Abar: "{\\bar A}",
      Bbar: "{\\bar B}",
      Kbar: "{\\bar K}",
      tr: "{\\operatorname{tr}}",
      diag: "{\\operatorname{diag}}",
      rank: "{\\operatorname{rank}}",
      spanop: "{\\operatorname{span}}",
      Real: "{\\operatorname{Re}}",
      Imag: "{\\operatorname{Im}}",
      spec: "{\\operatorname{spec}}",
      rhoop: "{\\rho}",
      Id: "{I}",
      poly: "{\\mathcal{P}}",
      GL: "{G_L}",
      inner: ["{\\left\\langle #1,#2\\right\\rangle}", 2],
      HiPPO: "{\\mathrm{HiPPO}}",
      LegS: "{\\mathrm{LegS}}",
      DPLR: "{\\mathrm{DPLR}}",
      NPLR: "{\\mathrm{NPLR}}",
      ifft: "{\\operatorname{IFFT}}",
      bigO: "{\\mathcal{O}}"
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">State Space Models</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/CosmoNaught/ssm-book"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/02-foundations/02-continuous-time.html">3. Continuous-Time Linear State Spaces</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../misc/icon-orange.svg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../../misc/icon-orange.svg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/00-front/preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/00-front/acknowledgements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgements</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/00-front/reader-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reader’s Guide</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/00-front/notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notation &amp; Preliminaries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/00-front/roadmap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Roadmap &amp; Contributing</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/01-introduction/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Introduction</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-introduction/index.html#sec-1-1" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.1 Sequences and memory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-introduction/index.html#sec-1-2" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.2 Recurrence, convolution, and attention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-introduction/index.html#sec-1-3" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.3 The state space route</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-introduction/index.html#sec-1-4" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.4 Why structure is needed</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-introduction/index.html#sec-1-5" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.5 State space layers and attention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-introduction/index.html#footnotes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Footnotes and references</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/01-introduction/index.html#exercises" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/02-foundations/01-state-as-memory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. State as Memory</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/01-state-as-memory.html#sec-2-1" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.1 What problem is the model trying to solve?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/01-state-as-memory.html#sec-2-2" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.2 The state equation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/01-state-as-memory.html#sec-2-3" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.3 What does it mean for the state to be memory?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/01-state-as-memory.html#sec-2-4" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.4 Notation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/01-state-as-memory.html#exercises" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/01-state-as-memory.html#footnotes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Footnotes and references</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/02-foundations/02-continuous-time.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">3. Continuous-Time Linear State Spaces</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/02-continuous-time.html#sec-3-1" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.1 Solving the differential equation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/02-continuous-time.html#sec-3-2" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.2 Lag and the impulse response</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/02-continuous-time.html#sec-3-3" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.3 How the eigenvalues of A shape memory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/02-continuous-time.html#sec-3-4" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.4 Fading memory and oscillatory memory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/02-continuous-time.html#sec-3-5" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.5 Linearity and time-invariance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/02-continuous-time.html#sec-3-6" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.6 From a scalar input to model dimension d_model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/02-continuous-time.html#sec-3-7" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.7 Notation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/02-continuous-time.html#exercises" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/02-continuous-time.html#footnotes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Footnotes and references</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/02-foundations/03-discretisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Discretisation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/03-discretisation.html#sec-4-1" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4.1 Why discretisation is needed</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/03-discretisation.html#sec-4-2" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4.2 Sampling and the exact one-step formula</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/03-discretisation.html#sec-4-3" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4.3 Holding the input constant between samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/03-discretisation.html#sec-4-4" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4.4 A second route: averaging the state dynamics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/03-discretisation.html#sec-4-5" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4.5 Eigenvalues and the step size as a timescale</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/03-discretisation.html#sec-4-6" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4.6 From recurrence to kernel</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/03-discretisation.html#sec-4-7" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4.7 Notation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/03-discretisation.html#exercises" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/03-discretisation.html#footnotes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Footnotes and references</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Recurrence, Convolution, and Toeplitz Maps</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html#sec-5-1" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.1 The question after discretisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html#sec-5-2" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.2 From the recurrence to a convolution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html#sec-5-3" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.3 What the discrete kernel means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html#sec-5-4" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.4 The convolution matrix</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html#sec-5-5" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.5 Why a fixed kernel requires time-invariance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html#sec-5-6" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.6 Cost of recurrence and convolution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html#sec-5-7" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.7 The kernel-generation problem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html#sec-5-8" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.8 Same model, two algorithms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html#sec-5-9" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5.9 Notation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html#exercises" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/04-recurrence-convolution-toeplitz.html#footnotes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Footnotes and references</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/02-foundations/05-transfer-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Transfer Functions and Kernel Generation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/05-transfer-functions.html#sec-6-1" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.1 Why another view is useful</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/05-transfer-functions.html#sec-6-2" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.2 The transfer function in diagonal coordinates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/05-transfer-functions.html#sec-6-3" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.3 The discrete generating function</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/05-transfer-functions.html#sec-6-4" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.4 The discrete generating function in diagonal coordinates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/05-transfer-functions.html#sec-6-5" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.5 Finite kernels as polynomials</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/05-transfer-functions.html#sec-6-6" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.6 What the resolvent changes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/05-transfer-functions.html#sec-6-7" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6.7 Notation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/05-transfer-functions.html#exercises" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/02-foundations/05-transfer-functions.html#footnotes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Footnotes and references</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/03-s4/06-memory-problem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. The Memory Problem</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/06-memory-problem.html#sec-7-1" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.1 A fixed state is not a stored history</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/06-memory-problem.html#sec-7-2" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.2 Slow decay is not enough</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/06-memory-problem.html#sec-7-3" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.3 Approximating the history by projection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/06-memory-problem.html#sec-7-4" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.4 Moving the history to a fixed interval</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/06-memory-problem.html#sec-7-5" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.5 A polynomial basis and its online dynamics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/06-memory-problem.html#sec-7-6" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7.6 Notation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/06-memory-problem.html#exercises" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/06-memory-problem.html#footnotes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Footnotes and references</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/03-s4/07-hippo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. HiPPO</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/07-hippo.html#sec-8-1" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8.1 From projection to a state equation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/07-hippo.html#sec-8-2" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8.2 The shifted Legendre basis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/07-hippo.html#sec-8-3" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8.3 Differentiating the coefficients</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/07-hippo.html#sec-8-4" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8.4 The HiPPO-LegS matrix</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/07-hippo.html#sec-8-5" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8.5 What the state contains</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/07-hippo.html#sec-8-6" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8.6 The time factor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/07-hippo.html#sec-8-7" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8.7 Notation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/07-hippo.html#exercises" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/07-hippo.html#footnotes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Footnotes and references</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/03-s4/08-structured-state-matrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Structured State Matrices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/08-structured-state-matrices.html#sec-9-1" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9.1 The cost of density</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/08-structured-state-matrices.html#sec-9-2" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9.2 Why diagonalisation would help</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/08-structured-state-matrices.html#sec-9-3" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9.3 Stable diagonalisation and cheap corrections</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/08-structured-state-matrices.html#sec-9-4" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9.4 The HiPPO matrix is normal plus rank one</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/08-structured-state-matrices.html#sec-9-5" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9.5 Why the DPLR form is useful</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/08-structured-state-matrices.html#sec-9-6" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9.6 Complex coordinates</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/08-structured-state-matrices.html#sec-9-7" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9.7 Notation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/08-structured-state-matrices.html#exercises" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/08-structured-state-matrices.html#footnotes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Footnotes and references</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/03-s4/09-s4-kernel-algorithm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10. The S4 Kernel Algorithm</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/09-s4-kernel-algorithm.html#sec-10-1" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10.1 The computational target</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/09-s4-kernel-algorithm.html#sec-10-2" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10.2 From kernel coefficients to Fourier samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/09-s4-kernel-algorithm.html#sec-10-3" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10.3 The bilinear discretisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/09-s4-kernel-algorithm.html#sec-10-4" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10.4 The diagonal resolvent as a Cauchy product</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/09-s4-kernel-algorithm.html#sec-10-5" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10.5 The low-rank correction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/09-s4-kernel-algorithm.html#sec-10-6" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10.6 Assembling the kernel and its cost</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/09-s4-kernel-algorithm.html#sec-10-7" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10.7 Notation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/09-s4-kernel-algorithm.html#exercises" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/09-s4-kernel-algorithm.html#footnotes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Footnotes and references</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../chapters/03-s4/10-diagonal-state-spaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11. Diagonal State Spaces: DSS, S4D, and S5</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#sec-11-1" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11.1 Removing the correction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#sec-11-2" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11.2 The continuous-time diagonal kernel</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#sec-11-3" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11.3 The discrete-time kernel and its Vandermonde form</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#sec-11-4" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11.4 Complex modes and real kernels</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#sec-11-5" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11.5 Why diagonalisation alone is not enough</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#sec-11-6" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11.6 Structured diagonal initialisations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#sec-11-7" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11.7 Stable parameterisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#sec-11-8" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11.8 Shared state and the parallel scan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#sec-11-9" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11.9 What the diagonal model preserves</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#sec-11-10" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11.10 Notation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#exercises" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/03-s4/10-diagonal-state-spaces.html#footnotes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Footnotes and references</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul>
  <li><a href="#sec-3-1" id="toc-sec-3-1" class="nav-link active" data-scroll-target="#sec-3-1">3.1 Solving the differential equation</a></li>
  <li><a href="#sec-3-2" id="toc-sec-3-2" class="nav-link" data-scroll-target="#sec-3-2">3.2 Lag and the impulse response</a></li>
  <li><a href="#sec-3-3" id="toc-sec-3-3" class="nav-link" data-scroll-target="#sec-3-3">3.3 How the eigenvalues of <span class="math inline">\(A\)</span> shape memory</a></li>
  <li><a href="#sec-3-4" id="toc-sec-3-4" class="nav-link" data-scroll-target="#sec-3-4">3.4 Fading memory and oscillatory memory</a>
  <ul class="collapse">
  <li><a href="#sec-3-4-1" id="toc-sec-3-4-1" class="nav-link" data-scroll-target="#sec-3-4-1">A fading one-dimensional memory</a></li>
  <li><a href="#sec-3-4-2" id="toc-sec-3-4-2" class="nav-link" data-scroll-target="#sec-3-4-2">A rotating two-dimensional memory</a></li>
  </ul></li>
  <li><a href="#sec-3-5" id="toc-sec-3-5" class="nav-link" data-scroll-target="#sec-3-5">3.5 Linearity and time-invariance</a></li>
  <li><a href="#sec-3-6" id="toc-sec-3-6" class="nav-link" data-scroll-target="#sec-3-6">3.6 From a scalar input to model dimension <span class="math inline">\(\dmodel\)</span></a></li>
  <li><a href="#sec-3-7" id="toc-sec-3-7" class="nav-link" data-scroll-target="#sec-3-7">3.7 Notation</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">3 Continuous-Time Linear State Spaces</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The state equation is local in time, but memory is not. The derivative only describes the next instant; the state at time <span class="math inline">\(t\)</span> contains the accumulated effect of all earlier inputs. Solving the differential equation turns the local update into an integral over the past, with the matrix exponential giving the weight assigned to each lag.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<section id="sec-3-1" class="level2">
<h2 class="anchored" data-anchor-id="sec-3-1">3.1 Solving the differential equation</h2>
<p>The equation</p>
<p><span class="math display">\[
x'(t)=Ax(t)+Bu(t)
\]</span></p>
<p>defines the model locally. It tells us how the state changes at an instant.</p>
<p>Memory is a global question. An input value from an earlier time <span class="math inline">\(s\)</span> affects the state at a later time <span class="math inline">\(t\)</span> through the full solution of the differential equation.</p>
<p>The current state is a weighted accumulation of past inputs, and the matrix <span class="math inline">\(A\)</span> determines the weights.</p>
<p>The one-dimensional case removes matrix notation while keeping the basic mechanism.</p>
<p>When <span class="math inline">\(N=1\)</span>, the state space is <span class="math inline">\(\R\)</span>. The matrices <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, and <span class="math inline">\(C\)</span> each have one entry. Write</p>
<p><span class="math display">\[
A=[a],
\qquad
B=[b],
\qquad
C=[c],
\]</span></p>
<p>with <span class="math inline">\(a,b,c\in\R\)</span>. Identifying each <span class="math inline">\(1\times 1\)</span> matrix with its single entry, the state equation becomes</p>
<p><span class="math display">\[
x'(t)=ax(t)+bu(t).
\]</span></p>
<p>First ignore the input. If <span class="math inline">\(u(t)=0\)</span>, then</p>
<p><span class="math display">\[
x'(t)=ax(t),
\]</span></p>
<p>whose solution is</p>
<p><span class="math display">\[
x(t)=e^{at}x(0).
\]</span></p>
<p>Thus <span class="math inline">\(a\)</span> controls the natural behaviour of the state. If <span class="math inline">\(a&lt;0\)</span>, the state decays. If <span class="math inline">\(a&gt;0\)</span>, the state grows. If <span class="math inline">\(a=0\)</span>, the state remains constant when no input is present.</p>
<p>Include the input. Rewrite</p>
<p><span class="math display">\[
x'(t)-ax(t)=bu(t).
\]</span></p>
<p>Multiplying both sides by <span class="math inline">\(e^{-at}\)</span> gives</p>
<p><span class="math display">\[
\frac{\dd}{\dd t}\left(e^{-at}x(t)\right)
=
e^{-at}bu(t).
\]</span></p>
<p>Integrating from <span class="math inline">\(0\)</span> to <span class="math inline">\(t\)</span>,</p>
<p><span class="math display">\[
e^{-at}x(t)-x(0)
=
\int_0^t e^{-as}bu(s)\dd s.
\]</span></p>
<p>Multiplying by <span class="math inline">\(e^{at}\)</span> gives</p>
<p><span class="math display">\[
x(t)
=
e^{at}x(0)
+
\int_0^t e^{a(t-s)}bu(s)\dd s.
\]</span></p>
<p>The solution gives a precise picture of memory. The input value <span class="math inline">\(u(s)\)</span> contributes to <span class="math inline">\(x(t)\)</span> with weight</p>
<p><span class="math display">\[
e^{a(t-s)}b.
\]</span></p>
<p>The quantity <span class="math inline">\(t-s\)</span> is the elapsed time between the input time <span class="math inline">\(s\)</span> and the present time <span class="math inline">\(t\)</span>. If <span class="math inline">\(a&lt;0\)</span>, then inputs farther in the past receive smaller weight. The scalar state is therefore an exponentially weighted summary of the past input.</p>
<p>For higher-dimensional states, the same idea holds, but scalar exponentials are replaced by matrix exponentials.</p>
<p>For a square matrix <span class="math inline">\(M\)</span>, the <strong>matrix exponential</strong> is defined by</p>
<p><span class="math display">\[
e^M
=
\sum_{k=0}^{\infty}\frac{M^k}{k!}
=
I+M+\frac{M^2}{2!}+\frac{M^3}{3!}+\cdots.
\]</span></p>
<p>The reason this object appears is that it solves the matrix version of exponential growth and decay. The function <span class="math inline">\(t\mapsto e^{At}\)</span> satisfies</p>
<p><span class="math display">\[
\frac{\dd}{\dd t}e^{At}=Ae^{At},
\qquad
e^{A\cdot 0}=I.
\]</span></p>
<p>Using the same integrating-factor argument as in the one-dimensional case, the solution of</p>
<p><span class="math display">\[
x'(t)=Ax(t)+Bu(t)
\]</span></p>
<p>is</p>
<p><span class="math display">\[
\boxed{
x(t)
=
e^{At}x(0)
+
\int_0^t e^{A(t-s)}Bu(s)\dd s.
}
\]</span></p>
<p>With the empty initial state <span class="math inline">\(x(0)=0\)</span>,</p>
<p><span class="math display">\[
x(t)
=
\int_0^t e^{A(t-s)}Bu(s)\dd s.
\]</span></p>
<p>This is the zero-state response, the part of the solution produced by the input alone.</p>
<p>The output is</p>
<p><span class="math display">\[
y(t)
=
Cx(t)
=
\int_0^t Ce^{A(t-s)}Bu(s)\dd s.
\]</span></p>
<p>The state equation and the convolution describe the same input-output map. The differential equation carries memory through <span class="math inline">\(x(t)\)</span>; the integral removes the state and shows the weight assigned to every past time.</p>
<p>The convolution formula specifies how the past is compressed into the state and read out. The input at time <span class="math inline">\(s\)</span> first enters through <span class="math inline">\(B\)</span>, then evolves for elapsed time <span class="math inline">\(t-s\)</span> through <span class="math inline">\(e^{A(t-s)}\)</span>, and is finally read out through <span class="math inline">\(C\)</span>.</p>
<p>In the MIMO case, the same expression holds with <span class="math inline">\(u(s)\in\R^p\)</span> and <span class="math inline">\(y(t)\in\R^q\)</span>. The product</p>
<p><span class="math display">\[
Ce^{A(t-s)}B
\]</span></p>
<p>is then a <span class="math inline">\(q\times p\)</span> matrix. Its <span class="math inline">\((r,i)\)</span> entry describes how the <span class="math inline">\(i\)</span>th input coordinate affects the <span class="math inline">\(r\)</span>th output coordinate after lag <span class="math inline">\(t-s\)</span>.</p>
</section>
<section id="sec-3-2" class="level2">
<h2 class="anchored" data-anchor-id="sec-3-2">3.2 Lag and the impulse response</h2>
<p>The output formula is</p>
<p><span class="math display">\[
y(t)
=
\int_0^t Ce^{A(t-s)}Bu(s)\dd s.
\]</span></p>
<p>Here <span class="math inline">\(s\)</span> is the time at which an input value was received, and <span class="math inline">\(t\)</span> is the time at which the output is evaluated. Since <span class="math inline">\(0\le s\le t\)</span>, the quantity</p>
<p><span class="math display">\[
t-s
\]</span></p>
<p>is the elapsed time between the input event and the output time. The elapsed time is called the lag. A recent input has small lag. A distant input has large lag.</p>
<p>The factor multiplying <span class="math inline">\(u(s)\)</span> is</p>
<p><span class="math display">\[
Ce^{A(t-s)}B.
\]</span></p>
<p>It depends on the input time <span class="math inline">\(s\)</span> only through the lag <span class="math inline">\(t-s\)</span>. The system’s response to a past input can therefore be described by a single function of the lag.</p>
<p>Define</p>
<p><span class="math display">\[
h(\tau)=Ce^{A\tau}B,
\qquad
\tau\ge 0,
\]</span></p>
<p>and set</p>
<p><span class="math display">\[
h(\tau)=0
\qquad
\text{for }\tau&lt;0.
\]</span></p>
<p>Then the output becomes</p>
<p><span class="math display">\[
y(t)
=
\int_0^t h(t-s)u(s)\dd s.
\]</span></p>
<p>The output has convolution form:</p>
<p><span class="math display">\[
y=h*u.
\]</span></p>
<p>The function <span class="math inline">\(h\)</span> is called the impulse response. It is the output pattern produced by an idealised unit input at one instant, and it gives the lag-dependent weight that connects each input value to later outputs.</p>
<p>For a MIMO system, <span class="math inline">\(h(\tau)\)</span> is matrix-valued:</p>
<p><span class="math display">\[
h(\tau)\in\R^{q\times p}.
\]</span></p>
<p>Each lag has an input-output matrix rather than a single scalar weight.</p>
<p>On a grid of lags, <span class="math inline">\(h(\tau)=Ce^{A\tau}B\)</span> separates a scalar decay from a decayed rotation. The scalar system <span class="math inline">\(A=[-1]\)</span> gives a single exponential. The <span class="math inline">\(2\times2\)</span> rotating system changes sign as it decays.</p>
<div id="e0cecfe8" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ssm_book.numpy_ref.continuous <span class="im">import</span> impulse_response</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ts <span class="op">=</span> np.array([<span class="fl">0.0</span>, <span class="fl">0.5</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">4.0</span>])</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># (i) scalar decay: A=[-1]</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>h_decay <span class="op">=</span> impulse_response([[<span class="op">-</span><span class="fl">1.0</span>]], [<span class="fl">1.0</span>], [<span class="fl">1.0</span>], ts).real.reshape(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># (ii) decayed rotation: eigenvalues -gamma +/- i*omega</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>gamma, omega <span class="op">=</span> <span class="fl">0.3</span>, <span class="fl">2.0</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> [[<span class="op">-</span>gamma, omega], [<span class="op">-</span>omega, <span class="op">-</span>gamma]]</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>h_rot <span class="op">=</span> impulse_response(A, [<span class="fl">1.0</span>, <span class="fl">0.0</span>], [<span class="fl">1.0</span>, <span class="fl">0.0</span>], ts).real.reshape(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">round</span>(np.stack([ts, h_decay, h_rot]), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>array([[ 0.    ,  0.5   ,  1.    ,  2.    ,  4.    ],
       [ 1.    ,  0.6065,  0.3679,  0.1353,  0.0183],
       [ 1.    ,  0.465 , -0.3083, -0.3587, -0.0438]])</code></pre>
</div>
</div>
<p>As the lag <span class="math inline">\(\tau\)</span> increases, the scalar response decreases monotonically because a single negative eigenvalue gives a fading weight. The rotating response decays in magnitude but changes sign, reflecting the oscillation produced by the imaginary parts <span class="math inline">\(\pm\omega\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../figures/fig-3-1-lag.svg" class="img-fluid figure-img" style="width:75.0%" alt="Two impulse-response curves against lag tau: a blue monotone exponential, and an orange decaying oscillation bounded by a dashed envelope, with dots at tau = 0, 0.5, 1, 2, 4, and both curves starting at 1."></p>
<figcaption>Figure 3.1. The impulse response <span class="math inline">\(h(\tau)=Ce^{A\tau}B\)</span> against the lag <span class="math inline">\(\tau\)</span>. The scalar system <span class="math inline">\(A=[-1]\)</span> gives a single fading exponential <span class="math inline">\(e^{-\tau}\)</span> (blue). The decayed rotation, with eigenvalues <span class="math inline">\(-0.3\pm 2i\)</span>, gives <span class="math inline">\(e^{-0.3\tau}\cos 2\tau\)</span> (orange), fading in magnitude but changing sign within the envelope <span class="math inline">\(\pm e^{-0.3\tau}\)</span> (dashed). The dots mark the lags <span class="math inline">\(\tau=0,0.5,1,2,4\)</span>. Both systems start at <span class="math inline">\(h(0)=CB=1\)</span>.</figcaption>
</figure>
</div>
<p>The convolution also has a simple construction. Write <span class="math inline">\(\delta\)</span> for the unit impulse, the idealised spike concentrated at time zero with <span class="math inline">\(\int \delta(r-s)f(r)\,\dd r=f(s)\)</span>. Every input is itself a superposition of shifted impulses,</p>
<p><span class="math display">\[
u(r)=\int_0^\infty u(s)\,\delta(r-s)\,\dd s,
\]</span></p>
<p>one spike at each instant <span class="math inline">\(s\)</span> weighted by <span class="math inline">\(u(s)\)</span>. At output time <span class="math inline">\(t\)</span>, causality restricts the contributing impulses to <span class="math inline">\(0\le s\le t\)</span>. The system turns each shifted impulse <span class="math inline">\(\delta(\cdot-s)\)</span> into the shifted impulse response <span class="math inline">\(h(t-s)\)</span>, and because the same matrices <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, <span class="math inline">\(C\)</span> apply at every time, the response to the whole input is the matching superposition,</p>
<p><span class="math display">\[
y(t)=\int_0^t h(t-s)\,u(s)\,\dd s,
\]</span></p>
<p>the same convolution as before. Each input impulse contributes one scaled, shifted copy of <span class="math inline">\(h\)</span>, and the copies add up.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../figures/fig-3-2-convolution.svg" class="img-fluid figure-img" style="width:92.0%" alt="Block diagram: input as an integral of shifted impulses, a linear time-invariant system box mapping delta to h, output as an integral of shifted impulse responses."></p>
<figcaption>Figure 3.2. Convolution from shifted impulses. The input is a superposition of shifted impulses. The state space model sends an impulse at time <span class="math inline">\(s\)</span> to the shifted impulse response <span class="math inline">\(h(t-s)\)</span>. By linearity the output is the matching superposition.</figcaption>
</figure>
</div>
</section>
<section id="sec-3-3" class="level2">
<h2 class="anchored" data-anchor-id="sec-3-3">3.3 How the eigenvalues of <span class="math inline">\(A\)</span> shape memory</h2>
<p>The impulse response is</p>
<p><span class="math display">\[
h(\tau)=Ce^{A\tau}B.
\]</span></p>
<p>Thus the behaviour of <span class="math inline">\(h\)</span> is controlled by <span class="math inline">\(e^{A\tau}\)</span>. The memory mechanisms are the functions that can appear inside this matrix exponential.</p>
<p>The clearest case is when <span class="math inline">\(A\)</span> can be diagonalised. Suppose <span class="math inline">\(A\)</span> has <span class="math inline">\(N\)</span> linearly independent eigenvectors</p>
<p><span class="math display">\[
v_1,\dots,v_N
\]</span></p>
<p>with corresponding eigenvalues</p>
<p><span class="math display">\[
\lambda_1,\dots,\lambda_N.
\]</span></p>
<p>Place the eigenvectors into the columns of a matrix</p>
<p><span class="math display">\[
V=
\begin{pmatrix}
| &amp; | &amp; &amp; |\\
v_1 &amp; v_2 &amp; \cdots &amp; v_N\\
| &amp; | &amp; &amp; |
\end{pmatrix},
\]</span></p>
<p>and define</p>
<p><span class="math display">\[
\Lambda=\diag(\lambda_1,\dots,\lambda_N).
\]</span></p>
<p>Then</p>
<p><span class="math display">\[
A=V\Lambda V^{-1}.
\]</span></p>
<p>In the eigenvector coordinate system, the action of <span class="math inline">\(A\)</span> separates into independent scalar modes. The matrix exponential becomes</p>
<p><span class="math display">\[
e^{A\tau}
=
Ve^{\Lambda\tau}V^{-1},
\]</span></p>
<p>where</p>
<p><span class="math display">\[
e^{\Lambda\tau}
=
\diag
\left(
e^{\lambda_1\tau},
\dots,
e^{\lambda_N\tau}
\right).
\]</span></p>
<p>So the impulse response is built from scalar exponential modes</p>
<p><span class="math display">\[
e^{\lambda_i\tau}.
\]</span></p>
<p>If</p>
<p><span class="math display">\[
\lambda_i=-\alpha_i+i\omega_i,
\]</span></p>
<p>then</p>
<p><span class="math display">\[
e^{\lambda_i\tau}
=
e^{-\alpha_i\tau}
\left(
\cos(\omega_i\tau)
+
i\sin(\omega_i\tau)
\right).
\]</span></p>
<p>The decay rate <span class="math inline">\(\alpha_i\)</span> controls growth or decay. The real part of the eigenvalue is <span class="math inline">\(-\alpha_i\)</span>, so a stable mode has <span class="math inline">\(\alpha_i&gt;0\)</span>. The imaginary part <span class="math inline">\(\omega_i\)</span> controls oscillation.</p>
<p>Thus:</p>
<ul>
<li>eigenvalues with negative real part give decaying modes;</li>
<li>eigenvalues close to the imaginary axis decay slowly and can preserve information for longer;</li>
<li>eigenvalues with nonzero imaginary part give oscillatory modes;</li>
<li>eigenvalues with positive real part grow and are usually unstable.</li>
</ul>
<p>When <span class="math inline">\(\Real\lambda_i&lt;0\)</span>, a useful way to measure the timescale of the mode is its half-life. The <strong>continuous half-life</strong> is the lag <span class="math inline">\(\tau_{1/2}\)</span> for which the magnitude has decayed by a factor of two:</p>
<p><span class="math display">\[
e^{(\Real\lambda_i)\tau_{1/2}}=\frac12.
\]</span></p>
<p>Therefore</p>
<p><span class="math display">\[
\boxed{
\tau_{1/2}=\frac{\log 2}{-\Real\lambda_i}=\frac{\log 2}{\alpha_i}.
}
\]</span></p>
<p>The half-life translates an eigenvalue into a memory length in continuous time.</p>
<p>The state matrix supplies the available memory modes through these eigenvalues.</p>
<p>The eigenvalues just used were complex, although the state matrix itself was real. Complex eigenvalues appear naturally when a real matrix contains rotations.</p>
<p>If <span class="math inline">\(A\)</span> is real and <span class="math inline">\(\lambda=-\alpha+i\omega\)</span> is an eigenvalue, then its complex conjugate <span class="math inline">\(\bar\lambda=-\alpha-i\omega\)</span> is also an eigenvalue. The corresponding complex modes combine to produce real sine and cosine terms. Thus complex eigenvalues do not force the state or output to become complex. They are often a compact way of describing a real two-dimensional rotation.</p>
<p>The simplest real rotation already appears in two dimensions. The matrix</p>
<p><span class="math display">\[
\begin{pmatrix}
0 &amp; \omega\\
-\omega &amp; 0
\end{pmatrix}
\]</span></p>
<p>has eigenvalues <span class="math inline">\(\pm i\omega\)</span>, but its action on <span class="math inline">\(\R^2\)</span> is planar rotation. Adding a negative multiple of the identity makes that rotation decay.</p>
<p>The diagonalisable case explains the main intuition, but not every matrix has a full set of eigenvectors. The same memory picture still holds, with one additional feature.</p>
<p>A Jordan block with eigenvalue <span class="math inline">\(\lambda\)</span> has the form</p>
<p><span class="math display">\[
J=\lambda I+R,
\]</span></p>
<p>where <span class="math inline">\(R\)</span> is nilpotent, meaning that some power of <span class="math inline">\(R\)</span> is zero. Since <span class="math inline">\(\lambda I\)</span> and <span class="math inline">\(R\)</span> commute,</p>
<p><span class="math display">\[
e^{J\tau}=e^{\lambda\tau}e^{R\tau}.
\]</span></p>
<p>If the block has size <span class="math inline">\(r\)</span>, then <span class="math inline">\(R^r=0\)</span>, so</p>
<p><span class="math display">\[
e^{R\tau}
=
I+\tau R+\frac{\tau^2}{2!}R^2+\cdots+\frac{\tau^{r-1}}{(r-1)!}R^{r-1}.
\]</span></p>
<p>Thus a non-diagonalisable block contributes exponential terms multiplied by polynomials in the lag:</p>
<p><span class="math display">\[
\tau^m e^{\lambda\tau}.
\]</span></p>
<p>The real part of <span class="math inline">\(\lambda\)</span> still controls exponential growth or decay. The Jordan structure adds polynomial factors on top of that exponential behaviour. For <span class="math inline">\(\Real\lambda=-\alpha&lt;0\)</span> the weight <span class="math inline">\(\tau^m e^{-\alpha\tau}\)</span> first grows like <span class="math inline">\(\tau^m\)</span> and only then decays, peaking near <span class="math inline">\(\tau=m/\alpha\)</span>, so a non-diagonalisable mode weights inputs at an intermediate lag most heavily rather than the most recent ones.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../figures/fig-3-3-decay.svg" class="img-fluid figure-img" style="width:80.0%" alt="Several exponential decay curves with a half-life construction on one."></p>
<figcaption>Figure 3.3. The real part of an eigenvalue is a memory length. Each curve is <span class="math inline">\(e^{-\alpha\tau}\)</span> for a decay rate <span class="math inline">\(\alpha&gt;0\)</span>. The half-life <span class="math inline">\(\tau_{1/2}=\log 2/\alpha\)</span> is marked on one.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../figures/fig-3-4-eigenvalues.svg" class="img-fluid figure-img" style="width:70.0%" alt="Complex plane with the stable left half-plane shaded, a conjugate pair on a circle of radius the eigenvalue magnitude, and the angle from the negative real axis."></p>
<figcaption>Figure 3.4. An eigenvalue <span class="math inline">\(\lambda=-\alpha+i\omega\)</span> of <span class="math inline">\(A\)</span> in the complex plane, with decay rate <span class="math inline">\(\alpha&gt;0\)</span> so that <span class="math inline">\(\Real\lambda=-\alpha\)</span> lies in the shaded stable region <span class="math inline">\(\Real\lambda&lt;0\)</span>. The decay rate <span class="math inline">\(\alpha\)</span> sets the fading and the imaginary part <span class="math inline">\(\omega\)</span> the oscillation frequency. The distance from the origin <span class="math inline">\(|\lambda|\)</span> measures the mode’s overall rate, and the angle <span class="math inline">\(\theta\)</span> from the negative real axis its balance of decay to oscillation. For a real matrix the eigenvalues occur in conjugate pairs <span class="math inline">\(\lambda,\bar\lambda\)</span>, mirrored across the real axis.</figcaption>
</figure>
</div>
</section>
<section id="sec-3-4" class="level2">
<h2 class="anchored" data-anchor-id="sec-3-4">3.4 Fading memory and oscillatory memory</h2>
<p>The memory of the model is built from modes of <span class="math inline">\(A\)</span>. The two simplest mechanisms are <strong>fading memory</strong> and <strong>oscillatory memory</strong>.</p>
<p>A real negative eigenvalue gives a decaying exponential, which behaves like a fading average of the past. A complex conjugate pair gives rotation, which can represent oscillatory or phase-like information.</p>
<p>Two examples isolate these mechanisms.</p>
<section id="sec-3-4-1" class="level3">
<h3 class="anchored" data-anchor-id="sec-3-4-1">A fading one-dimensional memory</h3>
<p>Take <span class="math inline">\(N=1\)</span> and write</p>
<p><span class="math display">\[
A=[a],
\qquad
B=[b],
\qquad
C=[c],
\]</span></p>
<p>with</p>
<p><span class="math display">\[
a&lt;0.
\]</span></p>
<p>The impulse response is</p>
<p><span class="math display">\[
h(\tau)=ce^{a\tau}b,
\qquad
\tau\ge 0.
\]</span></p>
<p>The output is</p>
<p><span class="math display">\[
y(t)
=
cb\int_0^t e^{a(t-s)}u(s)\dd s.
\]</span></p>
<p>The output is an exponentially weighted running total of the past input. The rate <span class="math inline">\(-a\)</span> determines how quickly older information is discounted. The half-life from <a href="#sec-3-3" class="quarto-xref">Section&nbsp;3</a> turns this rate into a number. For <span class="math inline">\(a=-1\)</span> the half-life is <span class="math inline">\(\log 2\approx 0.69\)</span>, so a lag of <span class="math inline">\(0.69\)</span> halves the weight, and at lag <span class="math inline">\(2\)</span> the weight is <span class="math inline">\(e^{-2}\approx 0.135\)</span>, the value the dots in Figure 3.1 mark on the blue curve.</p>
<p>This is the continuous-time exponential moving average, with <span class="math inline">\(-a\)</span> playing the part of the forgetting rate. A small <span class="math inline">\(-a\)</span> keeps a long memory and a large <span class="math inline">\(-a\)</span> forgets almost at once.</p>
<p>For example, if</p>
<p><span class="math display">\[
u(s)=1
\]</span></p>
<p>for all <span class="math inline">\(s\)</span>, then</p>
<p><span class="math display">\[
x(t)
=
b\int_0^t e^{a(t-s)}\dd s
=
\frac{b}{a}\left(e^{at}-1\right).
\]</span></p>
<p>Since <span class="math inline">\(a&lt;0\)</span>,</p>
<p><span class="math display">\[
x(t)\to -\frac{b}{a}
\qquad
\text{as }t\to\infty.
\]</span></p>
<p>The state approaches a finite value because old input is continuously discounted. The limit has a direct reading. Writing <span class="math inline">\(-b/a=b\int_0^\infty e^{a\tau}\dd\tau\)</span> shows it as <span class="math inline">\(b\)</span> times the total weight the system ever assigns to the past, so <span class="math inline">\(-b/a\)</span> is the gain the model applies to a constant input.</p>
</section>
<section id="sec-3-4-2" class="level3">
<h3 class="anchored" data-anchor-id="sec-3-4-2">A rotating two-dimensional memory</h3>
<p>A one-dimensional state can only move along a line. It can grow, decay, or stay fixed, but it cannot rotate. To get rotation, the state must have at least two dimensions.</p>
<p>Rotation matters because not all memory is well described as a fading average. Some signals contain periodic or phase-like structure. A rotating state can represent this kind of information.</p>
<p>Consider</p>
<p><span class="math display">\[
A=
\begin{pmatrix}
-\gamma &amp; \omega\\
-\omega &amp; -\gamma
\end{pmatrix},
\qquad
\gamma\ge 0,
\quad
\omega&gt;0.
\]</span></p>
<p>The parameter <span class="math inline">\(\gamma\)</span> controls decay, while <span class="math inline">\(\omega\)</span> controls angular speed. Write</p>
<p><span class="math display">\[
A=-\gamma I+\omega J,
\qquad
J=
\begin{pmatrix}
0 &amp; 1\\
-1 &amp; 0
\end{pmatrix}.
\]</span></p>
<p>The matrix <span class="math inline">\(J\)</span> is the basic generator of planar rotation. It satisfies</p>
<p><span class="math display">\[
J^2=-I.
\]</span></p>
<p>The identity gives the same sine-cosine pattern as the scalar exponential of an imaginary number. Since <span class="math inline">\(-\gamma I\)</span> commutes with <span class="math inline">\(\omega J\)</span>, the exponential factors as <span class="math inline">\(e^{A\tau}=e^{-\gamma\tau}e^{\omega J\tau}\)</span>. Splitting the series for <span class="math inline">\(e^{\omega J\tau}\)</span> into even and odd powers and using <span class="math inline">\(J^2=-I\)</span> collects the even terms into <span class="math inline">\(\cos(\omega\tau)I\)</span> and the odd terms into <span class="math inline">\(\sin(\omega\tau)J\)</span>, exactly as for <span class="math inline">\(e^{i\theta}\)</span>. Therefore</p>
<p><span class="math display">\[
e^{A\tau}
=
e^{-\gamma\tau}
\left(
\cos(\omega\tau)I+
\sin(\omega\tau)J
\right),
\]</span></p>
<p>or explicitly,</p>
<p><span class="math display">\[
e^{A\tau}
=
e^{-\gamma\tau}
\begin{pmatrix}
\cos(\omega\tau) &amp; \sin(\omega\tau)\\
-\sin(\omega\tau) &amp; \cos(\omega\tau)
\end{pmatrix}.
\]</span></p>
<p>The state rotates at angular frequency <span class="math inline">\(\omega\)</span>, while its magnitude decays at rate <span class="math inline">\(\gamma\)</span>.</p>
<p>The eigenvalues are</p>
<p><span class="math display">\[
-\gamma\pm i\omega.
\]</span></p>
<p>The eigenvalues match the general interpretation. The real part <span class="math inline">\(-\gamma\)</span> gives decay, and the imaginary parts <span class="math inline">\(\pm\omega\)</span> give oscillation.</p>
<p>A state space model can represent more than a fading average. By combining decaying and oscillating modes, a finite-dimensional state can encode both slowly varying and phase-like summaries of the input history.</p>
<p>The modes describe what the state can remember. They do not by themselves give a fixed convolution kernel. A fixed kernel appears only when the input-output map is both linear and time-invariant.</p>
</section>
</section>
<section id="sec-3-5" class="level2">
<h2 class="anchored" data-anchor-id="sec-3-5">3.5 Linearity and time-invariance</h2>
<p>The model is <strong>linear</strong> because <span class="math inline">\(x\)</span> and <span class="math inline">\(u\)</span> enter both equations only through matrix products:</p>
<p><span class="math display">\[
x'(t)=Ax(t)+Bu(t),
\qquad
y(t)=Cx(t).
\]</span></p>
<p>For zero initial state, the input-output map <span class="math inline">\(T:u\mapsto y\)</span> therefore satisfies</p>
<p><span class="math display">\[
T(\alpha u_1+\beta u_2)
=
\alpha T(u_1)+\beta T(u_2)
\]</span></p>
<p>for scalars <span class="math inline">\(\alpha,\beta\)</span>.</p>
<p>By the convolution formula</p>
<p><span class="math display">\[
y(t)=\int_0^t h(t-s)u(s)\dd s.
\]</span></p>
<p>The input <span class="math inline">\(u\)</span> appears only linearly inside the integral.</p>
<p>Linearity is restrictive. The model cannot multiply state coordinates by the input, cannot square the input, and cannot apply different dynamics depending on the content of the input. Nonlinear components can be placed around a state space model, but the state space model defined here is linear.</p>
<p>The same matrices control a second property. The model is <strong>time-invariant</strong> because the same matrices</p>
<p><span class="math display">\[
A,
\qquad
B,
\qquad
C
\]</span></p>
<p>are used at every time. The rule does not change as <span class="math inline">\(t\)</span> changes.</p>
<p>A delayed input pattern produces the same output pattern delayed by the same amount. The model does not change its rule merely because the same event happens later.</p>
<p>The impulse response, the kernel of this convolution, expresses time-invariance directly. The contribution of <span class="math inline">\(u(s)\)</span> to <span class="math inline">\(y(t)\)</span> depends on the lag</p>
<p><span class="math display">\[
t-s,
\]</span></p>
<p>not on the absolute values of <span class="math inline">\(s\)</span> and <span class="math inline">\(t\)</span> separately. A single function <span class="math inline">\(h\)</span> therefore applies at every time:</p>
<p><span class="math display">\[
y(t)=\int_0^t h(t-s)u(s)\dd s.
\]</span></p>
<p>Linearity and time-invariance together are abbreviated LTI. Their main consequence is the existence of a fixed convolution kernel.</p>
<p>If the matrices were allowed to vary with time, the weight from <span class="math inline">\(u(s)\)</span> to <span class="math inline">\(y(t)\)</span> would depend on the matrices used throughout the interval from <span class="math inline">\(s\)</span> to <span class="math inline">\(t\)</span>. The map could still be linear if those matrices were fixed in advance, but it would no longer be time-invariant, and the weight from <span class="math inline">\(u(s)\)</span> to <span class="math inline">\(y(t)\)</span> would depend on <span class="math inline">\(s\)</span> and <span class="math inline">\(t\)</span> separately rather than only on the lag <span class="math inline">\(t-s\)</span>.</p>
<p>If the matrices were allowed to depend on the input being processed, the situation would change further. Then the input would not merely pass through a fixed linear map. It would also help determine the map. The resulting input-output transformation would generally not be linear.</p>
</section>
<section id="sec-3-6" class="level2">
<h2 class="anchored" data-anchor-id="sec-3-6">3.6 From a scalar input to model dimension <span class="math inline">\(\dmodel\)</span></h2>
<p>A scalar input gives one stream. Neural sequence models usually store a vector at each position. If the model dimension is <span class="math inline">\(\dmodel\)</span>, then the input at time <span class="math inline">\(t\)</span> has the form</p>
<p><span class="math display">\[
u(t)\in\R^{\dmodel}.
\]</span></p>
<p>Write its coordinates as</p>
<p><span class="math display">\[
u(t)=
\begin{pmatrix}
u_1(t)\\
u_2(t)\\
\vdots\\
u_{\dmodel}(t)
\end{pmatrix}.
\]</span></p>
<p>A coordinate-wise state space layer applies one SISO state space model to each coordinate:</p>
<p><span class="math display">\[
x_d'(t)=A_d x_d(t)+B_d u_d(t),
\qquad
y_d(t)=C_d x_d(t),
\qquad
d=1,\dots,\dmodel.
\]</span></p>
<p>There is no mixing between coordinates inside these SISO state space models. The alternative would be one MIMO system with <span class="math inline">\(p=q=\dmodel\)</span>, which has a <span class="math inline">\(\dmodel\times\dmodel\)</span> matrix-valued impulse response at every lag and couples all coordinates through one shared state. The coordinate-wise layer instead gives <span class="math inline">\(\dmodel\)</span> scalar kernels, each with its own state of dimension <span class="math inline">\(N\)</span>, for <span class="math inline">\(O(\dmodel N)\)</span> total state against the coupled alternative. The independent layout is cheaper and keeps each coordinate readable on its own.</p>
<p>Any mixing across the model dimension is therefore performed outside this coordinate-wise state space operation, usually by position-wise linear maps surrounding the state space model.</p>
<p>The word “channel” is sometimes used in the literature for one coordinate of the model dimension. The term <strong>coordinate</strong> is used here unless quoting that terminology from a specific source.</p>
<p>Each coordinate requires its own scalar kernel <span class="math inline">\(Ce^{A\tau}B\)</span>. After discretisation, these kernels must be generated at a cost compatible with long sequences.</p>
</section>
<section id="sec-3-7" class="level2">
<h2 class="anchored" data-anchor-id="sec-3-7">3.7 Notation</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Meaning</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(h(\tau)\)</span></td>
<td>impulse response <span class="math inline">\(Ce^{A\tau}B\)</span></td>
<td>scalar or <span class="math inline">\(q\times p\)</span> matrix</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\lambda_i\)</span></td>
<td>eigenvalues of <span class="math inline">\(A\)</span></td>
<td><span class="math inline">\(\C\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\tau_{1/2}\)</span></td>
<td>continuous half-life of a decaying mode</td>
<td><span class="math inline">\(\R_{&gt;0}\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<p>Solving the continuous-time state equation turns a local differential equation into a memory formula. With zero initial state,</p>
<p><span class="math display">\[
x(t)=\int_0^t e^{A(t-s)}Bu(s)\,\dd s.
\]</span></p>
<p>The lag <span class="math inline">\(\tau=t-s\)</span> enters through <span class="math inline">\(e^{A\tau}\)</span>. Stable eigenvalues make old inputs fade; complex eigenvalues add oscillation as well as decay.</p>
<p>Reading the state with <span class="math inline">\(C\)</span> gives the impulse response</p>
<p><span class="math display">\[
h(\tau)=Ce^{A\tau}B.
\]</span></p>
<p>The same model can therefore be viewed as a recurrence in continuous time or as a convolution over the past. The initial condition adds a homogeneous term <span class="math inline">\(Ce^{At}x(0)\)</span>; the input-driven memory is the integral term.</p>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<ol type="1">
<li><p>Take the state equation <span class="math inline">\(x'(t)=Ax(t)+Bu(t)\)</span> with <span class="math inline">\(u(t)=0\)</span> for all <span class="math inline">\(t\)</span>. Show that <span class="math inline">\(x(t)=e^{At}x(0)\)</span> by differentiating <span class="math inline">\(e^{At}x(0)\)</span> and using <span class="math inline">\(\frac{\dd}{\dd t}e^{At}=Ae^{At}\)</span>, and confirm that it has the correct value at <span class="math inline">\(t=0\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>With <span class="math inline">\(u\equiv 0\)</span> the equation is <span class="math inline">\(x'(t)=Ax(t)\)</span>. Differentiate the candidate <span class="math inline">\(x(t)=e^{At}x(0)\)</span>, treating <span class="math inline">\(x(0)\)</span> as a constant vector:</p>
<p><span class="math display">\[
\frac{\dd}{\dd t}\bigl(e^{At}x(0)\bigr)
=\Bigl(\tfrac{\dd}{\dd t}e^{At}\Bigr)x(0)
=Ae^{At}x(0)
=Ax(t).
\]</span></p>
<p>So the candidate satisfies <span class="math inline">\(x'(t)=Ax(t)\)</span>. At <span class="math inline">\(t=0\)</span>, <span class="math inline">\(e^{A\cdot 0}=I\)</span>, hence <span class="math inline">\(x(0)=Ix(0)=x(0)\)</span>, the prescribed initial value. The candidate solves the equation and matches the initial condition, and the linear initial-value problem has a unique solution, so <span class="math inline">\(x(t)=e^{At}x(0)\)</span>.</p>
</div>
</div>
</div></li>
<li><p>Starting from <span class="math inline">\(\frac{\dd}{\dd t}\!\left(e^{-At}x(t)\right)=e^{-At}Bu(t)\)</span>, integrate from <span class="math inline">\(0\)</span> to <span class="math inline">\(t\)</span> and recover the zero-state response <span class="math inline">\(x(t)=\int_0^t e^{A(t-s)}Bu(s)\dd s\)</span> when <span class="math inline">\(x(0)=0\)</span>. State where the assumption <span class="math inline">\(x(0)=0\)</span> is used.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Integrate the given identity from <span class="math inline">\(0\)</span> to <span class="math inline">\(t\)</span>, using <span class="math inline">\(s\)</span> as the variable of integration:</p>
<p><span class="math display">\[
e^{-At}x(t)-e^{-A\cdot 0}x(0)
=\int_0^t e^{-As}Bu(s)\dd s.
\]</span></p>
<p>Since <span class="math inline">\(e^{-A\cdot 0}=I\)</span>, the left side is <span class="math inline">\(e^{-At}x(t)-x(0)\)</span>. Multiply through by <span class="math inline">\(e^{At}\)</span>:</p>
<p><span class="math display">\[
x(t)
=e^{At}x(0)
+\int_0^t e^{A(t-s)}Bu(s)\dd s,
\]</span></p>
<p>where <span class="math inline">\(e^{At}e^{-As}=e^{A(t-s)}\)</span> because <span class="math inline">\(At\)</span> and <span class="math inline">\(-As\)</span> commute. The assumption <span class="math inline">\(x(0)=0\)</span> is used only to drop the term <span class="math inline">\(e^{At}x(0)\)</span>, leaving the zero-state response <span class="math inline">\(x(t)=\int_0^t e^{A(t-s)}Bu(s)\dd s\)</span>. The convolution part is present regardless of the initial state; <span class="math inline">\(x(0)=0\)</span> removes the free decay of the initial condition.</p>
</div>
</div>
</div></li>
<li><p>Write a function that evaluates the impulse response <span class="math inline">\(h(\tau)=Ce^{A\tau}B\)</span> on a grid of lags, using a matrix exponential routine. For the scalar decay <span class="math inline">\(A=[-1]\)</span>, <span class="math inline">\(B=[1]\)</span>, <span class="math inline">\(C=[1]\)</span>, check that your values match <span class="math inline">\(e^{-\tau}\)</span> to within floating-point error, and report the largest absolute difference over the grid.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>impulse_response</code> forms <span class="math inline">\(Ce^{A\tau}B\)</span> at each lag with <code>scipy.linalg.expm</code>. For the scalar system the matrix exponential reduces to <span class="math inline">\(e^{-\tau}\)</span>, so the computed values should reproduce <span class="math inline">\(e^{-\tau}\)</span>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ssm_book.numpy_ref.continuous <span class="im">import</span> impulse_response</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>ts <span class="op">=</span> np.linspace(<span class="fl">0.0</span>, <span class="fl">5.0</span>, <span class="dv">51</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>h <span class="op">=</span> impulse_response([[<span class="op">-</span><span class="fl">1.0</span>]], [<span class="fl">1.0</span>], [<span class="fl">1.0</span>], ts).real.reshape(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.<span class="bu">max</span>(np.<span class="bu">abs</span>(h <span class="op">-</span> np.exp(<span class="op">-</span>ts))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The largest absolute difference over the grid is at the floating-point level and prints as <span class="math inline">\(0.0\)</span> in this run; the intended check is agreement within a small tolerance, not bit-for-bit equality, because a matrix-exponential routine is a numerical algorithm rather than a symbolic simplifier. A negative real eigenvalue gives a single fading exponential, the simplest form of memory.</p>
</div>
</div>
</div></li>
<li><p>For the decayed rotation <span class="math inline">\(A=\begin{pmatrix}-\gamma &amp; \omega\\ -\omega &amp; -\gamma\end{pmatrix}\)</span>, the eigenvalues are <span class="math inline">\(-\gamma\pm i\omega\)</span>. Compute the impulse response with <span class="math inline">\(B=(1,0)^\top\)</span> and <span class="math inline">\(C=(1,0)\)</span> for three settings: <span class="math inline">\((\gamma,\omega)=(1,0)\)</span>, <span class="math inline">\((0.1,0)\)</span>, and <span class="math inline">\((0.3,2)\)</span>. Describe how the decay rate and the presence of oscillation change across the three, and relate each to the eigenvalues.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>With <span class="math inline">\(B=(1,0)^\top\)</span> and <span class="math inline">\(C=(1,0)\)</span> the impulse response reads off the top-left entry of <span class="math inline">\(e^{A\tau}\)</span>, which is <span class="math inline">\(e^{-\gamma\tau}\cos(\omega\tau)\)</span>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ssm_book.numpy_ref.continuous <span class="im">import</span> impulse_response</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>ts <span class="op">=</span> np.array([<span class="fl">0.0</span>, <span class="fl">0.5</span>, <span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">4.0</span>])</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> gamma, omega <span class="kw">in</span> [(<span class="fl">1.0</span>, <span class="fl">0.0</span>), (<span class="fl">0.1</span>, <span class="fl">0.0</span>), (<span class="fl">0.3</span>, <span class="fl">2.0</span>)]:</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    A <span class="op">=</span> [[<span class="op">-</span>gamma, omega], [<span class="op">-</span>omega, <span class="op">-</span>gamma]]</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    h <span class="op">=</span> impulse_response(A, [<span class="fl">1.0</span>, <span class="fl">0.0</span>], [<span class="fl">1.0</span>, <span class="fl">0.0</span>], ts).real.reshape(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>((gamma, omega), np.<span class="bu">round</span>(h, <span class="dv">4</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>On the lags <span class="math inline">\(\tau=0,0.5,1,2,4\)</span> this gives</p>
<p><span class="math display">\[
\begin{aligned}
(\gamma,\omega)&amp;=(1,0): &amp;&amp; 1,\ 0.6065,\ 0.3679,\ 0.1353,\ 0.0183,\\
(\gamma,\omega)&amp;=(0.1,0): &amp;&amp; 1,\ 0.9512,\ 0.9048,\ 0.8187,\ 0.6703,\\
(\gamma,\omega)&amp;=(0.3,2): &amp;&amp; 1,\ 0.4650,\ -0.3083,\ -0.3587,\ -0.0438.
\end{aligned}
\]</span></p>
<p>With <span class="math inline">\(\omega=0\)</span> the eigenvalues are the real pair <span class="math inline">\(-\gamma,-\gamma\)</span> and the response is a pure decay <span class="math inline">\(e^{-\gamma\tau}\)</span>, with no sign change. Comparing the first two rows, <span class="math inline">\(\gamma=1\)</span> forgets quickly while <span class="math inline">\(\gamma=0.1\)</span> decays ten times more slowly and still retains most of its weight at <span class="math inline">\(\tau=4\)</span>. The third row has eigenvalues <span class="math inline">\(-0.3\pm 2i\)</span>: the magnitude decays at rate <span class="math inline">\(\gamma=0.3\)</span>, but the imaginary part <span class="math inline">\(\omega=2\)</span> rotates the state, so the response changes sign and is no longer monotone. The real part of the eigenvalue sets the decay rate; the imaginary part sets the oscillation.</p>
</div>
</div>
</div></li>
<li><p>Suppose <span class="math inline">\(A\)</span> has an eigenvalue <span class="math inline">\(\lambda\)</span> with <span class="math inline">\(\Real\lambda&gt;0\)</span>. Explain why the corresponding mode of <span class="math inline">\(e^{A\tau}\)</span> grows without bound as <span class="math inline">\(\tau\)</span> increases. If that mode is both excited by <span class="math inline">\(B\)</span> and read by <span class="math inline">\(C\)</span>, explain why the impulse response <span class="math inline">\(h(\tau)=Ce^{A\tau}B\)</span> does not define a fading memory. Contrast this with <span class="math inline">\(\Real\lambda&lt;0\)</span> and with <span class="math inline">\(\Real\lambda=0\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In the eigenbasis a mode for the eigenvalue <span class="math inline">\(\lambda\)</span> evolves as <span class="math inline">\(e^{\lambda\tau}\)</span>, with magnitude <span class="math inline">\(|e^{\lambda\tau}|=e^{(\Real\lambda)\tau}\)</span>. With <span class="math inline">\(\Real\lambda&gt;0\)</span> this magnitude grows without bound as <span class="math inline">\(\tau\to\infty\)</span>. Whenever <span class="math inline">\(B\)</span> excites this mode and <span class="math inline">\(C\)</span> reads it, the impulse response <span class="math inline">\(h(\tau)=Ce^{A\tau}B\)</span> inherits a term proportional to <span class="math inline">\(e^{(\Real\lambda)\tau}\)</span> and therefore grows rather than fades. A fading memory requires distant inputs to receive smaller weight, that is <span class="math inline">\(h(\tau)\to 0\)</span>; a growing mode gives the opposite, with the oldest inputs weighted most heavily, and the convolution <span class="math inline">\(\int_0^t h(t-s)u(s)\dd s\)</span> need not even converge as <span class="math inline">\(t\to\infty\)</span>.</p>
<p>When <span class="math inline">\(\Real\lambda&lt;0\)</span> the magnitude is <span class="math inline">\(e^{-\alpha\tau}\to 0\)</span> (decay rate <span class="math inline">\(\alpha&gt;0\)</span>), so the mode fades and contributes a decaying weight, the fading-memory regime. When <span class="math inline">\(\Real\lambda=0\)</span> the magnitude is <span class="math inline">\(e^{0}=1\)</span> for all <span class="math inline">\(\tau\)</span>: the mode neither grows nor decays. The input is then remembered with undiminished weight (a constant, if <span class="math inline">\(\omega=0\)</span>, or an undamped oscillation <span class="math inline">\(\cos\omega\tau\)</span> otherwise), so the memory persists rather than fades and sits on the boundary between the two regimes.</p>
</div>
</div>
</div></li>
</ol>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes and references</h2>

<ol>
<li id="fn1"><p>The continuous-time linear state space model, its solution by the matrix exponential, and the impulse response are standard in linear systems theory. The integrating-factor solution <span class="math inline">\(x(t)=e^{At}x(0)+\int_0^t e^{A(t-s)}Bu(s)\dd s\)</span>, the eigenvalue decomposition of <span class="math inline">\(e^{A\tau}\)</span>, and the Jordan-form correction are treated in standard accounts of linear systems <span class="citation" data-cites="kailath1980">(Kailath 1980)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<!-- Relocate (not duplicate) the page breadcrumb into the navbar brand container.
     On narrow screens its d-none class hides it and the secondary-nav breadcrumb takes over. -->
<script>
(function () {
  function moveBreadcrumb() {
    var brand = document.querySelector("#quarto-header .navbar-brand-container");
    var crumbs = document.querySelector("#title-block-header nav.quarto-title-breadcrumbs");
    if (brand && crumbs && !brand.contains(crumbs)) {
      crumbs.classList.add("ssm-navbar-breadcrumbs");
      brand.appendChild(crumbs);
    }
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", moveBreadcrumb);
  } else {
    moveBreadcrumb();
  }
})();
</script>
<!--
  Rebuild the bottom prev/next nav so it steps page-to-page.

  Quarto builds prev/next by stepping through every sidebar entry, including
  per-subsection anchors (...#sec-2-1-1), so "next" lands on a page's own first
  subsection (2.1 -> 2.1.1) rather than the next page (2.1 -> 2.2). Fold
  same-page subsection anchors into their page before computing prev/next.
-->
<script>
(function () {
  function normPath(p) {
    return p.replace(/index\.html$/, "").replace(/\/$/, "");
  }

  function fixPrevNext() {
    var menu = document.querySelector("#quarto-sidebar .sidebar-menu-container");
    var nav = document.querySelector(".page-navigation");
    if (!menu || !nav) return;

    // Ordered, de-duplicated list of pages, anchors folded into their page.
    var pages = [];
    var anchors = menu.querySelectorAll("a.sidebar-link");
    for (var n = 0; n < anchors.length; n++) {
      var a = anchors[n];
      if (!a.getAttribute("href")) continue;
      var path = normPath(a.pathname);
      var hasHash = !!a.hash;
      var last = pages.length ? pages[pages.length - 1] : null;
      if (!last || last.path !== path) {
        pages.push({
          path: path,
          href: a.href.split("#")[0],
          title: a.textContent.trim(),
          titled: !hasHash
        });
      } else if (!hasHash && !last.titled) {
        // a no-fragment link to the same page carries the page's own title
        last.href = a.href.split("#")[0];
        last.title = a.textContent.trim();
        last.titled = true;
      }
    }

    var here = normPath(location.pathname);
    var i = -1;
    for (var k = 0; k < pages.length; k++) {
      if (pages[k].path === here) { i = k; break; }
    }
    if (i === -1) return;

    function setSide(selector, page) {
      var box = nav.querySelector(selector);
      if (!box) return;
      var link = box.querySelector("a");
      if (!link) return;
      if (!page) { box.style.display = "none"; return; }
      link.setAttribute("href", page.href);
      var text = link.querySelector(".nav-page-text");
      if (text) text.textContent = page.title;
    }

    setSide(".nav-page-previous", i > 0 ? pages[i - 1] : null);
    setSide(".nav-page-next", i < pages.length - 1 ? pages[i + 1] : null);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", fixPrevNext);
  } else {
    fixPrevNext();
  }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/CosmoNaught\.github\.io\/ssm-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/02-foundations/01-state-as-memory.html#footnotes" class="pagination-link" aria-label="Footnotes and references">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Footnotes and references</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/02-foundations/02-continuous-time.html#sec-3-1" class="pagination-link" aria-label="3.1 Solving the differential equation">
        <span class="nav-page-text">3.1 Solving the differential equation</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>©&nbsp;2026 Cosmo Santoni. Text under <a href="https://creativecommons.org/licenses/by/4.0/">CC&nbsp;BY&nbsp;4.0</a>; code under <a href="https://www.apache.org/licenses/LICENSE-2.0">Apache&nbsp;2.0</a>.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>